[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = "26.0.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_db_pools = { version = "0.2.0", default-features = false }
serde = "1.0.219"
toml = "0.8.20"
